async (page) => {
  const check = (value, message) => {if (!value) throw Error(message);};
  await page.waitForFunction(() => document.querySelector('#connection').textContent === 'Connected to your desktop');
  await page.locator('#title').fill('Modal test');
  await page.locator('#save').click();
  await page.waitForSelector('.note-card');
  const remove = page.locator('.card-actions').getByRole('button', {name:'Delete', exact:true});
  await remove.click();
  const modal = page.locator('dialog[open]');
  await modal.waitFor();
  check(await page.locator(':focus').textContent() === 'Cancel', 'Cancel should receive focus');
  await page.keyboard.press('Tab');
  check(await page.locator(':focus').evaluate(el => !!el.closest('dialog')), 'Focus stays in modal');
  await page.keyboard.press('Escape');
  await modal.waitFor({state:'detached'});
  check(await page.locator('.note-card').count() === 1, 'Escape must not delete');
  check(await remove.evaluate(el => el === document.activeElement), 'Focus returns to trigger');
  await page.locator('#body').fill('Unsaved draft');
  await page.locator('#new-note').click();
  await modal.getByRole('button', {name:'Cancel', exact:true}).click();
  check(await page.locator('#body').inputValue() === 'Unsaved draft', 'Cancel preserves draft');
  await page.locator('#new-note').click();
  await modal.getByRole('button', {name:'Discard', exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#body').value === '');
  await page.evaluate(() => {
    window.promptResults = [];
    dialog(['One', 'Two', 'Cancel'], '<img src=x onerror=alert(1)>').then(value => promptResults.push(value));
    dialog(['OK'], 'Second queued prompt').then(value => promptResults.push(value));
  });
  await modal.waitFor();
  check(await modal.locator('img').count() === 0, 'Prompt must render as text');
  await modal.getByRole('button', {name:'Two', exact:true}).click();
  await modal.getByText('Second queued prompt').waitFor();
  await modal.getByRole('button', {name:'OK', exact:true}).click();
  await page.waitForFunction(() => promptResults.length === 2);
  check(JSON.stringify(await page.evaluate(() => promptResults)) === '["Two","OK"]', 'Queued choices resolve independently');
  await remove.click();
  await page.setViewportSize({width:390,height:844});
  check(await modal.evaluate(el => el.getBoundingClientRect().right <= innerWidth), 'Modal fits mobile');
  await page.screenshot({path:'/tmp/sticky-modal-web.png'});
  await modal.getByRole('button', {name:'Delete', exact:true}).click();
  await page.waitForFunction(() => !document.querySelector('.note-card'));
  await page.locator('#quit').click();
  await modal.getByRole('button', {name:'Cancel', exact:true}).click();
  check(await page.locator('#connection').textContent() === 'Connected to your desktop', 'Cancel keeps app running');
  await page.locator('#quit').click();
  await modal.getByRole('button', {name:'Quit', exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#connection').textContent === 'App stopped');
  return {passed:['focus trap and restoration', 'Escape', 'discard/cancel', 'dynamic text and buttons', 'queued prompts', 'mobile layout', 'confirmed deletion', 'quit/cancel']};
}
